#!/bin/bash
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_002/
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_003/
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_004/
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_005/
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_006/
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_007/
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_008/
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_009/
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_010/
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_011/
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_013/
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_014/
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_015/
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_016/
#python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_017/
python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_018/
python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_019/
python KeyframeSelection_flownet.py --dir /playpen/throat/Endoscope_Study/UNC_HN_Laryngoscopy_020/
